name: Component Detection

on:
  workflow_dispatch:
  push:

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #dotnet restore /home/runner/work/NugetCentral/NugetCentral/CentralPackageManagementExample.sln
      #dotnet build --no-incremental /home/runner/work/NugetCentral/NugetCentral/CentralPackageManagementExample.sln
      - run: |
          dotnet restore CentralPackageManagementExample.sln
          dotnet build --no-incremental CentralPackageManagementExample.sln
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.2
      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Snapshots
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          #image-ref: '.'
          github-pat: '${{ secrets.GITHUB_TOKEN }}' 
